account: 162808325377
region: us-east-1
prefix_name: calcloud-hst
topic_name: pipeline-topic
queue_subscriptions:
    batch-queue: 
      - batch-init
    sync-queue: 
      - dataset-processed
    archive-queue: 
      - dataset-synced
message_types:
  - batch-init,            # Batch message received by pipeline,  forwarded to scheduler.
  - batch-started,         # Pipeline has started queueing datasets for processing.
  - batch-done,            # All datasets have been archived, errored, or failed.
  - batch-error,           # Calcloud code had a bug or failure while setting up the batch.
  - batch-fail,            # AWS resource malfunction of some kind while setting up the batch.
  - cluster-provisioning,  # Calcloud has started acquiring processing resources. (enumerated here)
  - cluster-provisioned,   # Calcloud has acquired needed processing resources. (enumerated here)
  - cluster-error,         # STScI code failed somewhere for some reason.
  - cluster-fail,          # An AWS Resource failed for some reason.
  - dataset-queued,        # One dataset has been queued (defines requirements, resource bin)
  - dataset-started,       # One dataset started processing inside the container.
  - dataset-processed,     # One dataset completed processing without errors.
  - dataset-synced,        # One dataset's output files downloaded to STScI.
  - dataset-archived,      # One dataset's output files have been added to the archive.
  - dataset-error,         # STScI code failed somewhere for some reason.
  - dataset-fail,          # An AWS Resource failed for some reason.
message_senders:
  - trigger
  - scheduler
  - caldp
  - syncer
  - archive
tags: {}
s3_output_root: pipeline-outputs